export type NameGender = "girl" | "boy" | "unisex";

export interface BabyName {
  name: string;
  gender: NameGender;
  origin: string;
  meaning: string;
}

export const BABY_NAMES: BabyName[] = [
  { name: "Olivia", gender: "girl", origin: "Latin", meaning: "Olive tree" },
  { name: "Amelia", gender: "girl", origin: "Germanic", meaning: "Work, industrious" },
  { name: "Sophia", gender: "girl", origin: "Greek", meaning: "Wisdom" },
  { name: "Isabella", gender: "girl", origin: "Hebrew", meaning: "Devoted to God" },
  { name: "Luna", gender: "girl", origin: "Latin", meaning: "Moon" },
  { name: "Aria", gender: "girl", origin: "Italian", meaning: "Air, melody" },
  { name: "Willow", gender: "girl", origin: "English", meaning: "Willow tree, grace" },
  { name: "Nova", gender: "girl", origin: "Latin", meaning: "New" },
  { name: "Hazel", gender: "girl", origin: "English", meaning: "The hazelnut tree" },
  { name: "Violet", gender: "girl", origin: "Latin", meaning: "Purple flower" },
  { name: "Maya", gender: "girl", origin: "Sanskrit", meaning: "Illusion, dream" },
  { name: "Clara", gender: "girl", origin: "Latin", meaning: "Clear, bright" },
  { name: "Freya", gender: "girl", origin: "Norse", meaning: "Lady, goddess of love" },
  { name: "Ivy", gender: "girl", origin: "English", meaning: "Faithfulness" },
  { name: "Stella", gender: "girl", origin: "Latin", meaning: "Star" },
  { name: "Liam", gender: "boy", origin: "Irish", meaning: "Strong-willed warrior" },
  { name: "Noah", gender: "boy", origin: "Hebrew", meaning: "Rest, comfort" },
  { name: "Oliver", gender: "boy", origin: "Latin", meaning: "Olive tree" },
  { name: "Elijah", gender: "boy", origin: "Hebrew", meaning: "My God is Yahweh" },
  { name: "Theodore", gender: "boy", origin: "Greek", meaning: "Gift of God" },
  { name: "Ezra", gender: "boy", origin: "Hebrew", meaning: "Help" },
  { name: "Atlas", gender: "boy", origin: "Greek", meaning: "Enduring, to carry" },
  { name: "Leo", gender: "boy", origin: "Latin", meaning: "Lion" },
  { name: "Silas", gender: "boy", origin: "Latin", meaning: "Forest, woods" },
  { name: "Jasper", gender: "boy", origin: "Persian", meaning: "Treasurer, precious stone" },
  { name: "Miles", gender: "boy", origin: "Latin", meaning: "Soldier" },
  { name: "August", gender: "boy", origin: "Latin", meaning: "Magnificent, revered" },
  { name: "Felix", gender: "boy", origin: "Latin", meaning: "Happy, fortunate" },
  { name: "Rowan", gender: "unisex", origin: "Gaelic", meaning: "Little redhead, rowan tree" },
  { name: "River", gender: "unisex", origin: "English", meaning: "Flowing water" },
  { name: "Sage", gender: "unisex", origin: "Latin", meaning: "Wise, herb" },
  { name: "Phoenix", gender: "unisex", origin: "Greek", meaning: "Mythical bird, rebirth" },
  { name: "Emerson", gender: "unisex", origin: "English", meaning: "Son of Emery" },
  { name: "Quinn", gender: "unisex", origin: "Irish", meaning: "Wise, intelligent" },
  { name: "Skylar", gender: "unisex", origin: "Dutch", meaning: "Scholar" },

  // Expanded with additional top-ranked US names (per Social Security
  // Administration historical data, the same public dataset referenced by
  // github.com/hamaluik/nomdebebe) to broaden coverage beyond the original
  // curated set.
  { name: "Emma", gender: "girl", origin: "Germanic", meaning: "Universal, whole" },
  { name: "Charlotte", gender: "girl", origin: "French", meaning: "Free" },
  { name: "Ava", gender: "girl", origin: "Latin", meaning: "Life, bird" },
  { name: "Mia", gender: "girl", origin: "Italian", meaning: "Mine, beloved" },
  { name: "Evelyn", gender: "girl", origin: "English", meaning: "Wished-for child" },
  { name: "Harper", gender: "girl", origin: "English", meaning: "Harp player" },
  { name: "Camila", gender: "girl", origin: "Latin", meaning: "Attendant at a religious ceremony" },
  { name: "Gianna", gender: "girl", origin: "Italian", meaning: "God is gracious" },
  { name: "Abigail", gender: "girl", origin: "Hebrew", meaning: "My father's joy" },
  { name: "Ella", gender: "girl", origin: "Germanic", meaning: "Fairy maiden" },
  { name: "Scarlett", gender: "girl", origin: "English", meaning: "Bright red" },
  { name: "Grace", gender: "girl", origin: "Latin", meaning: "Grace, blessing" },
  { name: "Chloe", gender: "girl", origin: "Greek", meaning: "Blooming, fertility" },
  { name: "Penelope", gender: "girl", origin: "Greek", meaning: "Weaver" },
  { name: "Layla", gender: "girl", origin: "Arabic", meaning: "Night, dark beauty" },
  { name: "Riley", gender: "unisex", origin: "Irish", meaning: "Valiant, courageous" },
  { name: "Zoey", gender: "girl", origin: "Greek", meaning: "Life" },
  { name: "Nora", gender: "girl", origin: "Irish", meaning: "Light, honor" },
  { name: "Lily", gender: "girl", origin: "English", meaning: "Lily flower, purity" },
  { name: "Eleanor", gender: "girl", origin: "Greek", meaning: "Light" },
  { name: "Hannah", gender: "girl", origin: "Hebrew", meaning: "Grace, favor" },
  { name: "Lillian", gender: "girl", origin: "Latin", meaning: "Lily flower" },
  { name: "Addison", gender: "girl", origin: "English", meaning: "Child of Adam" },
  { name: "Aubrey", gender: "girl", origin: "English", meaning: "Elf ruler" },
  { name: "Ellie", gender: "girl", origin: "English", meaning: "Bright, shining one" },
  { name: "Natalie", gender: "girl", origin: "Latin", meaning: "Born on Christmas day" },
  { name: "Zoe", gender: "girl", origin: "Greek", meaning: "Life" },
  { name: "Leah", gender: "girl", origin: "Hebrew", meaning: "Weary, delicate" },
  { name: "Hazelynn", gender: "girl", origin: "English", meaning: "Hazel tree, gentle" },
  { name: "Aurora", gender: "girl", origin: "Latin", meaning: "Dawn" },
  { name: "Savannah", gender: "girl", origin: "Spanish", meaning: "Flat tropical grassland" },
  { name: "Audrey", gender: "girl", origin: "English", meaning: "Noble strength" },
  { name: "Brooklyn", gender: "girl", origin: "English", meaning: "Water stream, place name" },
  { name: "Bella", gender: "girl", origin: "Italian", meaning: "Beautiful" },
  { name: "Claire", gender: "girl", origin: "French", meaning: "Clear, bright" },
  { name: "Skyler", gender: "unisex", origin: "Dutch", meaning: "Scholar" },
  { name: "Genesis", gender: "girl", origin: "Greek", meaning: "Origin, beginning" },
  { name: "Naomi", gender: "girl", origin: "Hebrew", meaning: "Pleasantness" },
  { name: "Elena", gender: "girl", origin: "Greek", meaning: "Bright, shining light" },
  { name: "Cora", gender: "girl", origin: "Greek", meaning: "Maiden" },

  { name: "James", gender: "boy", origin: "Hebrew", meaning: "Supplanter" },
  { name: "Benjamin", gender: "boy", origin: "Hebrew", meaning: "Son of the right hand" },
  { name: "Lucas", gender: "boy", origin: "Latin", meaning: "Light-giving, from Lucania" },
  { name: "Mason", gender: "boy", origin: "English", meaning: "Stoneworker" },
  { name: "Ethan", gender: "boy", origin: "Hebrew", meaning: "Strong, firm" },
  { name: "Alexander", gender: "boy", origin: "Greek", meaning: "Defender of the people" },
  { name: "Henry", gender: "boy", origin: "Germanic", meaning: "Ruler of the household" },
  { name: "Jackson", gender: "boy", origin: "English", meaning: "Son of Jack" },
  { name: "Sebastian", gender: "boy", origin: "Greek", meaning: "Venerable, revered" },
  { name: "Aiden", gender: "boy", origin: "Irish", meaning: "Little fire" },
  { name: "Matthew", gender: "boy", origin: "Hebrew", meaning: "Gift of God" },
  { name: "Samuel", gender: "boy", origin: "Hebrew", meaning: "God has heard" },
  { name: "David", gender: "boy", origin: "Hebrew", meaning: "Beloved" },
  { name: "Joseph", gender: "boy", origin: "Hebrew", meaning: "God will add" },
  { name: "Carter", gender: "boy", origin: "English", meaning: "Transporter of goods by cart" },
  { name: "Owen", gender: "boy", origin: "Welsh", meaning: "Young warrior, well-born" },
  { name: "Wyatt", gender: "boy", origin: "English", meaning: "Brave in war" },
  { name: "John", gender: "boy", origin: "Hebrew", meaning: "God is gracious" },
  { name: "Jack", gender: "boy", origin: "English", meaning: "God is gracious" },
  { name: "Luke", gender: "boy", origin: "Greek", meaning: "Light-giving" },
  { name: "Jayden", gender: "boy", origin: "Hebrew", meaning: "God has heard" },
  { name: "Dylan", gender: "boy", origin: "Welsh", meaning: "Son of the sea" },
  { name: "Grayson", gender: "boy", origin: "English", meaning: "Son of the steward" },
  { name: "Levi", gender: "boy", origin: "Hebrew", meaning: "Joined, attached" },
  { name: "Isaac", gender: "boy", origin: "Hebrew", meaning: "He will laugh" },
  { name: "Gabriel", gender: "boy", origin: "Hebrew", meaning: "God is my strength" },
  { name: "Julian", gender: "boy", origin: "Latin", meaning: "Youthful, downy-bearded" },
  { name: "Anthony", gender: "boy", origin: "Latin", meaning: "Priceless, praiseworthy" },
  { name: "Christopher", gender: "boy", origin: "Greek", meaning: "Bearer of Christ" },
  { name: "Andrew", gender: "boy", origin: "Greek", meaning: "Manly, brave" },
  { name: "Joshua", gender: "boy", origin: "Hebrew", meaning: "God is salvation" },
  { name: "Nathan", gender: "boy", origin: "Hebrew", meaning: "He gave" },
  { name: "Caleb", gender: "boy", origin: "Hebrew", meaning: "Whole-hearted, devoted" },
  { name: "Ryan", gender: "boy", origin: "Irish", meaning: "Little king" },
  { name: "Adrian", gender: "boy", origin: "Latin", meaning: "From Hadria, dark one" },
  { name: "Eli", gender: "boy", origin: "Hebrew", meaning: "Ascended, uplifted" },
  { name: "Nolan", gender: "boy", origin: "Irish", meaning: "Champion, noble" },
  { name: "Christian", gender: "boy", origin: "Latin", meaning: "Follower of Christ" },
  { name: "Aaron", gender: "boy", origin: "Hebrew", meaning: "High mountain, exalted" },

  { name: "Charlie", gender: "unisex", origin: "Germanic", meaning: "Free man" },
  { name: "Finley", gender: "unisex", origin: "Irish", meaning: "Fair-haired warrior" },
  { name: "Reese", gender: "unisex", origin: "Welsh", meaning: "Ardor, enthusiasm" },
  { name: "Elliot", gender: "unisex", origin: "Hebrew", meaning: "The Lord is my God" },
  { name: "Avery", gender: "unisex", origin: "English", meaning: "Ruler of the elves" },
  { name: "Peyton", gender: "unisex", origin: "English", meaning: "Fighting man's estate" },
  { name: "Morgan", gender: "unisex", origin: "Welsh", meaning: "Sea-born, great and bright" },
  { name: "Sawyer", gender: "unisex", origin: "English", meaning: "Woodcutter" },
  { name: "Dakota", gender: "unisex", origin: "Sioux", meaning: "Friend, ally" },

  // Second expansion — broader coverage across more letters and cultures.
  { name: "Adalyn", gender: "girl", origin: "Germanic", meaning: "Noble one" },
  { name: "Adeline", gender: "girl", origin: "French", meaning: "Noble" },
  { name: "Alaina", gender: "girl", origin: "Irish", meaning: "Fair, beautiful" },
  { name: "Alice", gender: "girl", origin: "Germanic", meaning: "Noble kind" },
  { name: "Alina", gender: "girl", origin: "Slavic", meaning: "Bright, beautiful" },
  { name: "Allison", gender: "girl", origin: "Germanic", meaning: "Noble kind" },
  { name: "Amara", gender: "girl", origin: "Igbo", meaning: "Grace" },
  { name: "Amelie", gender: "girl", origin: "French", meaning: "Work, industrious" },
  { name: "Anastasia", gender: "girl", origin: "Greek", meaning: "Resurrection" },
  { name: "Andrea", gender: "girl", origin: "Greek", meaning: "Womanly, strong" },
  { name: "Angela", gender: "girl", origin: "Greek", meaning: "Messenger, angel" },
  { name: "Anna", gender: "girl", origin: "Hebrew", meaning: "Grace, favor" },
  { name: "Annabelle", gender: "girl", origin: "French", meaning: "Loving, beautiful" },
  { name: "Ariana", gender: "girl", origin: "Greek", meaning: "Most holy" },
  { name: "Arianna", gender: "girl", origin: "Greek", meaning: "Most holy" },
  { name: "Aspen", gender: "girl", origin: "English", meaning: "Aspen tree" },
  { name: "Athena", gender: "girl", origin: "Greek", meaning: "Goddess of wisdom" },
  { name: "Autumn", gender: "girl", origin: "English", meaning: "Fall season" },
  { name: "Bailey", gender: "unisex", origin: "English", meaning: "Bailiff, steward" },
  { name: "Bianca", gender: "girl", origin: "Italian", meaning: "White, pure" },
  { name: "Blake", gender: "unisex", origin: "English", meaning: "Fair-haired, dark" },
  { name: "Brianna", gender: "girl", origin: "Irish", meaning: "Noble, strong" },
  { name: "Brielle", gender: "girl", origin: "French", meaning: "Strong, from Brie" },
  { name: "Brooke", gender: "girl", origin: "English", meaning: "Small stream" },
  { name: "Callie", gender: "girl", origin: "Greek", meaning: "Most beautiful" },
  { name: "Camille", gender: "girl", origin: "French", meaning: "Attendant, young ceremonial helper" },
  { name: "Cara", gender: "girl", origin: "Italian", meaning: "Beloved" },
  { name: "Caroline", gender: "girl", origin: "French", meaning: "Free woman" },
  { name: "Cassandra", gender: "girl", origin: "Greek", meaning: "One who entangles men" },
  { name: "Cecilia", gender: "girl", origin: "Latin", meaning: "Blind, from the Roman clan Caecilius" },
  { name: "Celeste", gender: "girl", origin: "Latin", meaning: "Heavenly" },
  { name: "Charlize", gender: "girl", origin: "Germanic", meaning: "Free woman" },
  { name: "Cheyenne", gender: "girl", origin: "Native American", meaning: "People of a different language" },
  { name: "Coraline", gender: "girl", origin: "Greek", meaning: "Maiden" },
  { name: "Daisy", gender: "girl", origin: "English", meaning: "Day's eye, flower" },
  { name: "Dakotah", gender: "girl", origin: "Sioux", meaning: "Friend, ally" },
  { name: "Delilah", gender: "girl", origin: "Hebrew", meaning: "Delicate, weak" },
  { name: "Diana", gender: "girl", origin: "Latin", meaning: "Divine, goddess of the moon" },
  { name: "Eden", gender: "unisex", origin: "Hebrew", meaning: "Place of pleasure, delight" },
  { name: "Elaina", gender: "girl", origin: "Greek", meaning: "Bright, shining light" },
  { name: "Eliana", gender: "girl", origin: "Hebrew", meaning: "My God has answered" },
  { name: "Elise", gender: "girl", origin: "Hebrew", meaning: "God is my oath" },
  { name: "Elsie", gender: "girl", origin: "Scottish", meaning: "God is my oath" },
  { name: "Emery", gender: "unisex", origin: "Germanic", meaning: "Brave, powerful" },
  { name: "Emilia", gender: "girl", origin: "Latin", meaning: "Rival, eager" },
  { name: "Esme", gender: "girl", origin: "French", meaning: "Esteemed, loved" },
  { name: "Esther", gender: "girl", origin: "Persian", meaning: "Star" },
  { name: "Eva", gender: "girl", origin: "Hebrew", meaning: "Life" },
  { name: "Everly", gender: "girl", origin: "English", meaning: "From the boar meadow" },
  { name: "Faith", gender: "girl", origin: "English", meaning: "Trust, belief" },
  { name: "Fiona", gender: "girl", origin: "Gaelic", meaning: "Fair, white" },
  { name: "Gabriella", gender: "girl", origin: "Hebrew", meaning: "God is my strength" },
  { name: "Genevieve", gender: "girl", origin: "French", meaning: "Woman of the people" },
  { name: "Georgia", gender: "girl", origin: "Greek", meaning: "Farmer, earth-worker" },
  { name: "Gracie", gender: "girl", origin: "Latin", meaning: "Grace, blessing" },
  { name: "Hadley", gender: "unisex", origin: "English", meaning: "Heather field" },
  { name: "Haley", gender: "girl", origin: "English", meaning: "Hay meadow" },
  { name: "Harmony", gender: "girl", origin: "Latin", meaning: "Agreement, concord" },
  { name: "Harlow", gender: "unisex", origin: "English", meaning: "Rock hill, army hill" },
  { name: "Hattie", gender: "girl", origin: "Germanic", meaning: "Ruler of the household" },
  { name: "Heidi", gender: "girl", origin: "Germanic", meaning: "Of noble birth" },
  { name: "Imani", gender: "unisex", origin: "Swahili", meaning: "Faith" },
  { name: "Iris", gender: "girl", origin: "Greek", meaning: "Rainbow" },
  { name: "Isabelle", gender: "girl", origin: "Hebrew", meaning: "Devoted to God" },
  { name: "Isla", gender: "girl", origin: "Scottish", meaning: "Island" },
  { name: "Jade", gender: "girl", origin: "Spanish", meaning: "Precious green stone" },
  { name: "Jasmine", gender: "girl", origin: "Persian", meaning: "Jasmine flower" },
  { name: "Josephine", gender: "girl", origin: "Hebrew", meaning: "God will add" },
  { name: "Journey", gender: "unisex", origin: "English", meaning: "A trip, passage" },
  { name: "Juniper", gender: "girl", origin: "Latin", meaning: "Juniper tree, youthful" },
  { name: "Juliette", gender: "girl", origin: "Latin", meaning: "Youthful" },
  { name: "Kaia", gender: "girl", origin: "Hawaiian", meaning: "Sea" },
  { name: "Kate", gender: "girl", origin: "Greek", meaning: "Pure" },
  { name: "Katherine", gender: "girl", origin: "Greek", meaning: "Pure" },
  { name: "Kayla", gender: "girl", origin: "Hebrew", meaning: "Crown of laurels" },
  { name: "Kennedy", gender: "unisex", origin: "Irish", meaning: "Helmeted chief" },
  { name: "Kinsley", gender: "girl", origin: "English", meaning: "King's meadow" },
  { name: "Kylie", gender: "girl", origin: "Aboriginal Australian", meaning: "Boomerang" },
  { name: "Lauren", gender: "girl", origin: "Latin", meaning: "From Laurentum, laurel" },
  { name: "Lena", gender: "girl", origin: "Greek", meaning: "Bright, shining light" },
  { name: "Leilani", gender: "girl", origin: "Hawaiian", meaning: "Heavenly flower" },
  { name: "Lucia", gender: "girl", origin: "Latin", meaning: "Light" },
  { name: "Lucy", gender: "girl", origin: "Latin", meaning: "Light" },
  { name: "Madeline", gender: "girl", origin: "Greek", meaning: "Woman from Magdala" },
  { name: "Madison", gender: "girl", origin: "English", meaning: "Son of Maud" },
  { name: "Maeve", gender: "girl", origin: "Irish", meaning: "She who intoxicates" },
  { name: "Margaret", gender: "girl", origin: "Greek", meaning: "Pearl" },
  { name: "Margot", gender: "girl", origin: "French", meaning: "Pearl" },
  { name: "Mackenzie", gender: "unisex", origin: "Irish", meaning: "Child of the wise leader" },
  { name: "Melody", gender: "girl", origin: "Greek", meaning: "Song, melody" },
  { name: "Mila", gender: "girl", origin: "Slavic", meaning: "Gracious, dear" },
  { name: "Millie", gender: "girl", origin: "Germanic", meaning: "Work, industrious" },
  { name: "Molly", gender: "girl", origin: "Hebrew", meaning: "Bitter, star of the sea" },
  { name: "Nadia", gender: "girl", origin: "Slavic", meaning: "Hope" },
  { name: "Nevaeh", gender: "girl", origin: "English", meaning: "Heaven spelled backward" },
  { name: "Nyla", gender: "girl", origin: "Arabic", meaning: "Winner" },
  { name: "Olive", gender: "girl", origin: "Latin", meaning: "Olive tree, peace" },
  { name: "Paisley", gender: "girl", origin: "Scottish", meaning: "Church, cemetery" },
  { name: "Paloma", gender: "girl", origin: "Spanish", meaning: "Dove" },
  { name: "Piper", gender: "girl", origin: "English", meaning: "Pipe player" },
  { name: "Reagan", gender: "unisex", origin: "Irish", meaning: "Little king" },
  { name: "Rebecca", gender: "girl", origin: "Hebrew", meaning: "To bind, join" },
  { name: "Remi", gender: "unisex", origin: "French", meaning: "Oarsman" },
  { name: "Rosalie", gender: "girl", origin: "Latin", meaning: "Rose" },
  { name: "Rose", gender: "girl", origin: "Latin", meaning: "Rose flower" },
  { name: "Ruby", gender: "girl", origin: "Latin", meaning: "Red precious stone" },
  { name: "Ruth", gender: "girl", origin: "Hebrew", meaning: "Friend, companion" },
  { name: "Sadie", gender: "girl", origin: "Hebrew", meaning: "Princess" },
  { name: "Samantha", gender: "girl", origin: "Aramaic", meaning: "Listener, told by God" },
  { name: "Sarah", gender: "girl", origin: "Hebrew", meaning: "Princess" },
  { name: "Selena", gender: "girl", origin: "Greek", meaning: "Moon" },
  { name: "Serenity", gender: "girl", origin: "Latin", meaning: "Peaceful, calm" },
  { name: "Sienna", gender: "girl", origin: "Italian", meaning: "Reddish-brown, from Siena" },
  { name: "Sophie", gender: "girl", origin: "Greek", meaning: "Wisdom" },
  { name: "Summer", gender: "girl", origin: "English", meaning: "Summer season" },
  { name: "Talia", gender: "girl", origin: "Hebrew", meaning: "Dew from heaven" },
  { name: "Valentina", gender: "girl", origin: "Latin", meaning: "Strong, healthy" },
  { name: "Vanessa", gender: "girl", origin: "Greek", meaning: "Butterfly" },
  { name: "Vera", gender: "girl", origin: "Russian", meaning: "Faith, truth" },
  { name: "Victoria", gender: "girl", origin: "Latin", meaning: "Victory" },
  { name: "Violeta", gender: "girl", origin: "Latin", meaning: "Purple flower" },
  { name: "Vivian", gender: "girl", origin: "Latin", meaning: "Alive, lively" },
  { name: "Willa", gender: "girl", origin: "Germanic", meaning: "Resolute protector" },
  { name: "Wren", gender: "girl", origin: "English", meaning: "Small bird" },
  { name: "Zara", gender: "girl", origin: "Arabic", meaning: "Blooming flower, princess" },
  { name: "Zoie", gender: "girl", origin: "Greek", meaning: "Life" },

  { name: "Adam", gender: "boy", origin: "Hebrew", meaning: "Man, earth" },
  { name: "Alan", gender: "boy", origin: "Celtic", meaning: "Handsome, cheerful" },
  { name: "Albert", gender: "boy", origin: "Germanic", meaning: "Noble, bright" },
  { name: "Alfred", gender: "boy", origin: "English", meaning: "Wise counselor" },
  { name: "Amos", gender: "boy", origin: "Hebrew", meaning: "Carried, burdened" },
  { name: "Angel", gender: "unisex", origin: "Greek", meaning: "Messenger of God" },
  { name: "Angelo", gender: "boy", origin: "Greek", meaning: "Messenger, angel" },
  { name: "Archer", gender: "boy", origin: "English", meaning: "Bowman" },
  { name: "Arlo", gender: "boy", origin: "English", meaning: "Fortified hill" },
  { name: "Arthur", gender: "boy", origin: "Celtic", meaning: "Bear, noble, strong" },
  { name: "Asher", gender: "boy", origin: "Hebrew", meaning: "Happy, blessed" },
  { name: "Austin", gender: "boy", origin: "Latin", meaning: "Great, magnificent" },
  { name: "Axel", gender: "boy", origin: "Scandinavian", meaning: "Father of peace" },
  { name: "Barrett", gender: "boy", origin: "Germanic", meaning: "Strong as a bear" },
  { name: "Bennett", gender: "boy", origin: "Latin", meaning: "Blessed" },
  { name: "Bentley", gender: "boy", origin: "English", meaning: "Meadow with bent grass" },
  { name: "Bode", gender: "boy", origin: "Germanic", meaning: "Messenger" },
  { name: "Bradley", gender: "boy", origin: "English", meaning: "Broad meadow" },
  { name: "Braxton", gender: "boy", origin: "English", meaning: "Brock's town" },
  { name: "Brayden", gender: "boy", origin: "Irish", meaning: "Broad hill" },
  { name: "Brody", gender: "boy", origin: "Irish", meaning: "Ditch, muddy place" },
  { name: "Bruce", gender: "boy", origin: "Scottish", meaning: "From the brushwood thicket" },
  { name: "Bryce", gender: "boy", origin: "Welsh", meaning: "Speckled, freckled" },
  { name: "Cameron", gender: "unisex", origin: "Scottish", meaning: "Crooked nose" },
  { name: "Camden", gender: "boy", origin: "Scottish", meaning: "Winding valley" },
  { name: "Carson", gender: "unisex", origin: "Scottish", meaning: "Son of the marsh-dwellers" },
  { name: "Charles", gender: "boy", origin: "Germanic", meaning: "Free man" },
  { name: "Cole", gender: "boy", origin: "English", meaning: "Coal-black, swarthy" },
  { name: "Colton", gender: "boy", origin: "English", meaning: "Coal town" },
  { name: "Connor", gender: "boy", origin: "Irish", meaning: "Lover of hounds" },
  { name: "Cooper", gender: "boy", origin: "English", meaning: "Barrel maker" },
  { name: "Cruz", gender: "unisex", origin: "Spanish", meaning: "Cross" },
  { name: "Damian", gender: "boy", origin: "Greek", meaning: "To tame, subdue" },
  { name: "Daniel", gender: "boy", origin: "Hebrew", meaning: "God is my judge" },
  { name: "Declan", gender: "boy", origin: "Irish", meaning: "Full of goodness" },
  { name: "Dominic", gender: "boy", origin: "Latin", meaning: "Belonging to the Lord" },
  { name: "Dominik", gender: "boy", origin: "Latin", meaning: "Belonging to the Lord" },
  { name: "Easton", gender: "boy", origin: "English", meaning: "East-facing place" },
  { name: "Edward", gender: "boy", origin: "English", meaning: "Wealthy guardian" },
  { name: "Elias", gender: "boy", origin: "Hebrew", meaning: "The Lord is my God" },
  { name: "Emmett", gender: "boy", origin: "English", meaning: "Universal, whole" },
  { name: "Enzo", gender: "boy", origin: "Italian", meaning: "Ruler of the household" },
  { name: "Ezekiel", gender: "boy", origin: "Hebrew", meaning: "God will strengthen" },
  { name: "Finn", gender: "boy", origin: "Irish", meaning: "Fair, white" },
  { name: "Francis", gender: "boy", origin: "Latin", meaning: "Free man, from France" },
  { name: "Frank", gender: "boy", origin: "Germanic", meaning: "Free man" },
  { name: "Gael", gender: "boy", origin: "Irish", meaning: "Gaelic speaker" },
  { name: "Gavin", gender: "boy", origin: "Welsh", meaning: "White hawk" },
  { name: "George", gender: "boy", origin: "Greek", meaning: "Farmer, earth-worker" },
  { name: "Grady", gender: "boy", origin: "Irish", meaning: "Noble, illustrious" },
  { name: "Grant", gender: "boy", origin: "English", meaning: "Great, large" },
  { name: "Greyson", gender: "boy", origin: "English", meaning: "Son of the steward" },
  { name: "Griffin", gender: "boy", origin: "Welsh", meaning: "Strong lord, mythical creature" },
  { name: "Harrison", gender: "boy", origin: "English", meaning: "Son of Harry" },
  { name: "Hayden", gender: "unisex", origin: "English", meaning: "Hedged valley" },
  { name: "Hudson", gender: "boy", origin: "English", meaning: "Son of Hudde" },
  { name: "Hunter", gender: "unisex", origin: "English", meaning: "One who hunts" },
  { name: "Ian", gender: "boy", origin: "Scottish", meaning: "God is gracious" },
  { name: "Ivan", gender: "boy", origin: "Slavic", meaning: "God is gracious" },
  { name: "Jace", gender: "boy", origin: "Greek", meaning: "Healer" },
  { name: "Jaxon", gender: "boy", origin: "English", meaning: "Son of Jack" },
  { name: "Jeremiah", gender: "boy", origin: "Hebrew", meaning: "God will exalt" },
  { name: "Jonah", gender: "boy", origin: "Hebrew", meaning: "Dove" },
  { name: "Jonathan", gender: "boy", origin: "Hebrew", meaning: "God has given" },
  { name: "Jordan", gender: "unisex", origin: "Hebrew", meaning: "To flow down, descend" },
  { name: "Jose", gender: "boy", origin: "Spanish", meaning: "God will add" },
  { name: "Josiah", gender: "boy", origin: "Hebrew", meaning: "God supports" },
  { name: "Judah", gender: "boy", origin: "Hebrew", meaning: "Praised" },
  { name: "Jude", gender: "boy", origin: "Hebrew", meaning: "Praised" },
  { name: "Kai", gender: "unisex", origin: "Hawaiian", meaning: "Sea" },
  { name: "Kayden", gender: "boy", origin: "American", meaning: "Fighter" },
  { name: "Keegan", gender: "boy", origin: "Irish", meaning: "Small flame, fiery" },
  { name: "Kevin", gender: "boy", origin: "Irish", meaning: "Handsome, beloved" },
  { name: "Kingston", gender: "boy", origin: "English", meaning: "King's town" },
  { name: "Knox", gender: "boy", origin: "Scottish", meaning: "Round hill" },
  { name: "Landon", gender: "boy", origin: "English", meaning: "Long hill" },
  { name: "Lincoln", gender: "boy", origin: "English", meaning: "Settlement by the pool" },
  { name: "Logan", gender: "unisex", origin: "Scottish", meaning: "Small hollow" },
  { name: "Lorenzo", gender: "boy", origin: "Latin", meaning: "From Laurentum, laurel" },
  { name: "Louis", gender: "boy", origin: "Germanic", meaning: "Famous warrior" },
  { name: "Marcus", gender: "boy", origin: "Latin", meaning: "Dedicated to Mars" },
  { name: "Mateo", gender: "boy", origin: "Spanish", meaning: "Gift of God" },
  { name: "Maverick", gender: "boy", origin: "American", meaning: "Independent, unbranded" },
  { name: "Maxwell", gender: "boy", origin: "Scottish", meaning: "Great stream" },
  { name: "Micah", gender: "boy", origin: "Hebrew", meaning: "Who is like God" },
  { name: "Michael", gender: "boy", origin: "Hebrew", meaning: "Who is like God" },
  { name: "Nathaniel", gender: "boy", origin: "Hebrew", meaning: "Gift of God" },
  { name: "Nicholas", gender: "boy", origin: "Greek", meaning: "Victory of the people" },
  { name: "Oscar", gender: "boy", origin: "Irish", meaning: "God spear, deer lover" },
  { name: "Parker", gender: "unisex", origin: "English", meaning: "Keeper of the park" },
  { name: "Patrick", gender: "boy", origin: "Latin", meaning: "Nobleman" },
  { name: "Paul", gender: "boy", origin: "Latin", meaning: "Small, humble" },
  { name: "Peter", gender: "boy", origin: "Greek", meaning: "Rock" },
  { name: "Preston", gender: "boy", origin: "English", meaning: "Priest's town" },
  { name: "Rafael", gender: "boy", origin: "Hebrew", meaning: "God has healed" },
  { name: "Ralph", gender: "boy", origin: "Germanic", meaning: "Wolf counsel" },
  { name: "Raymond", gender: "boy", origin: "Germanic", meaning: "Wise protector" },
  { name: "Reid", gender: "boy", origin: "Scottish", meaning: "Red-haired" },
  { name: "Robert", gender: "boy", origin: "Germanic", meaning: "Bright fame" },
  { name: "Roman", gender: "boy", origin: "Latin", meaning: "Citizen of Rome" },
  { name: "Ronan", gender: "boy", origin: "Irish", meaning: "Little seal" },
  { name: "Ryder", gender: "boy", origin: "English", meaning: "Mounted warrior" },
  { name: "Santiago", gender: "boy", origin: "Spanish", meaning: "Saint James" },
  { name: "Simon", gender: "boy", origin: "Hebrew", meaning: "He has heard" },
  { name: "Solomon", gender: "boy", origin: "Hebrew", meaning: "Peace" },
  { name: "Spencer", gender: "unisex", origin: "English", meaning: "Steward, dispenser of provisions" },
  { name: "Stephen", gender: "boy", origin: "Greek", meaning: "Crown, garland" },
  { name: "Sullivan", gender: "boy", origin: "Irish", meaning: "Dark eyes" },
  { name: "Thomas", gender: "boy", origin: "Aramaic", meaning: "Twin" },
  { name: "Timothy", gender: "boy", origin: "Greek", meaning: "Honoring God" },
  { name: "Tobias", gender: "boy", origin: "Hebrew", meaning: "God is good" },
  { name: "Tristan", gender: "boy", origin: "Welsh", meaning: "Tumult, noise" },
  { name: "Tucker", gender: "boy", origin: "English", meaning: "One who processes cloth" },
  { name: "Tyler", gender: "boy", origin: "English", meaning: "Maker of tiles" },
  { name: "Vincent", gender: "boy", origin: "Latin", meaning: "Conquering" },
  { name: "Walter", gender: "boy", origin: "Germanic", meaning: "Ruler of the army" },
  { name: "Weston", gender: "boy", origin: "English", meaning: "Western town" },
  { name: "William", gender: "boy", origin: "Germanic", meaning: "Resolute protector" },
  { name: "Xavier", gender: "boy", origin: "Basque", meaning: "New house, bright" },
  { name: "Zachary", gender: "boy", origin: "Hebrew", meaning: "God has remembered" },
  { name: "Zane", gender: "boy", origin: "Hebrew", meaning: "God is gracious" },

  { name: "Alexis", gender: "unisex", origin: "Greek", meaning: "Defender, helper" },
  { name: "Ariel", gender: "unisex", origin: "Hebrew", meaning: "Lion of God" },
  { name: "Corey", gender: "unisex", origin: "Irish", meaning: "From the hollow" },
  { name: "Dallas", gender: "unisex", origin: "Scottish", meaning: "From the meadow dwelling" },
  { name: "Devon", gender: "unisex", origin: "English", meaning: "From Devonshire" },
  { name: "Drew", gender: "unisex", origin: "Welsh", meaning: "Wise" },
  { name: "Ellis", gender: "unisex", origin: "Welsh", meaning: "Benevolent" },
  { name: "Frankie", gender: "unisex", origin: "Germanic", meaning: "Free man" },
  { name: "Jamie", gender: "unisex", origin: "Hebrew", meaning: "Supplanter" },
  { name: "Jesse", gender: "unisex", origin: "Hebrew", meaning: "Gift, God exists" },
  { name: "Jordyn", gender: "unisex", origin: "Hebrew", meaning: "To flow down, descend" },
  { name: "Justice", gender: "unisex", origin: "Latin", meaning: "Righteousness, fairness" },
  { name: "Lane", gender: "unisex", origin: "English", meaning: "A narrow road" },
  { name: "London", gender: "unisex", origin: "English", meaning: "Place name, fortress of the moon" },
  { name: "Marley", gender: "unisex", origin: "English", meaning: "Pleasant meadow near the lake" },
  { name: "Milan", gender: "unisex", origin: "Slavic", meaning: "Gracious, dear" },
  { name: "Oakley", gender: "unisex", origin: "English", meaning: "Oak tree meadow" },
  { name: "Remington", gender: "unisex", origin: "English", meaning: "Raven estate" },
  { name: "Robin", gender: "unisex", origin: "Germanic", meaning: "Bright fame" },
  { name: "Rory", gender: "unisex", origin: "Irish", meaning: "Red king" },
  { name: "Rylan", gender: "unisex", origin: "English", meaning: "Land where rye is grown" },
  { name: "Sam", gender: "unisex", origin: "Hebrew", meaning: "God has heard" },
  { name: "Shiloh", gender: "unisex", origin: "Hebrew", meaning: "Peaceful one, his gift" },
  { name: "Sidney", gender: "unisex", origin: "English", meaning: "Wide meadow" },
  { name: "Sutton", gender: "unisex", origin: "English", meaning: "From the southern homestead" },
  { name: "Tatum", gender: "unisex", origin: "English", meaning: "Cheerful bringer of joy" },
  { name: "Taylor", gender: "unisex", origin: "English", meaning: "Tailor" },
  { name: "True", gender: "unisex", origin: "English", meaning: "Faithful, honest" },
  { name: "Wilder", gender: "unisex", origin: "English", meaning: "Untamed, wild" },
  { name: "Winter", gender: "unisex", origin: "English", meaning: "Winter season" },
];

export function filterNames(gender: NameGender | "all", letter: string): BabyName[] {
  return BABY_NAMES.filter((n) => {
    const genderMatch = gender === "all" || n.gender === gender;
    const letterMatch = !letter || n.name.toLowerCase().startsWith(letter.toLowerCase());
    return genderMatch && letterMatch;
  });
}

export function randomName(gender: NameGender | "all"): BabyName {
  const pool = gender === "all" ? BABY_NAMES : BABY_NAMES.filter((n) => n.gender === gender);
  return pool[Math.floor(Math.random() * pool.length)];
}
