// Approximate week-by-week fetal size data for the growth slider.
// Figures are commonly cited estimates for general education, not clinical data.

export type ComparisonTheme = "fruit" | "food" | "geeky";

export interface WeekData {
  week: number;
  comparison: string;
  lengthCm: number;
  weightG: number;
  note: string;
}

const STATS: [number, number, number, string][] = [
  [4, 0.1, 0.1, "Implantation is just occurring."],
  [5, 0.3, 0.1, "The neural tube begins to form."],
  [6, 0.6, 0.2, "A heartbeat may be detectable."],
  [7, 1.3, 1, "Arm and leg buds are forming."],
  [8, 1.6, 1, "Fingers and toes start to form."],
  [9, 2.3, 2, "Essential organs begin to function."],
  [10, 3.1, 4, "Vital organs are formed and starting to function."],
  [11, 4.1, 7, "Baby can open and close fists."],
  [12, 5.4, 14, "Reflexes are developing."],
  [13, 7.4, 23, "Fingerprints are forming."],
  [14, 8.7, 43, "Baby can make facial expressions."],
  [15, 10.1, 70, "Legs are growing longer than arms."],
  [16, 11.6, 100, "Baby may start sensing light."],
  [17, 13, 140, "A protective layer of fat starts forming."],
  [18, 14.2, 190, "Baby's ears are in their final position."],
  [19, 15.3, 240, "Vernix, a protective coating, is forming."],
  [20, 25.6, 300, "You may be able to find out the sex."],
  [21, 26.7, 360, "Baby's movements become more coordinated."],
  [22, 27.8, 430, "Eyebrows and eyelids are fully formed."],
  [23, 28.9, 501, "Baby's hearing continues to develop."],
  [24, 30, 600, "Lungs are developing branches for future air sacs."],
  [25, 34.6, 660, "Baby is practicing breathing motions."],
  [26, 35.6, 760, "Eyes begin to open."],
  [27, 36.6, 875, "Baby can respond to sound and light."],
  [28, 37.6, 1005, "Baby can now blink."],
  [29, 38.6, 1153, "Muscles and lungs continue maturing."],
  [30, 39.9, 1319, "Baby's brain is developing rapidly."],
  [31, 41.1, 1502, "Baby can turn its head side to side."],
  [32, 42.4, 1702, "Baby is practicing swallowing and 'breathing'."],
  [33, 43.7, 1918, "Bones are hardening, except the skull."],
  [34, 45, 2146, "Baby's central nervous system is maturing."],
  [35, 46.2, 2383, "Kidneys are fully developed."],
  [36, 47.4, 2622, "Baby is gaining roughly 28g a day."],
  [37, 48.6, 2859, "Considered 'early term'."],
  [38, 49.8, 3083, "Baby's grip is getting stronger."],
  [39, 50.7, 3288, "Baby is considered full term."],
  [40, 51.2, 3462, "Any day now!"],
];

const COMPARISONS: Record<ComparisonTheme, Record<number, string>> = {
  fruit: {
    4: "Poppy seed",
    5: "Sesame seed",
    6: "Lentil",
    7: "Blueberry",
    8: "Raspberry",
    9: "Grape",
    10: "Kumquat",
    11: "Fig",
    12: "Lime",
    13: "Lemon",
    14: "Peach",
    15: "Apple",
    16: "Avocado",
    17: "Pear",
    18: "Bell pepper",
    19: "Heirloom tomato",
    20: "Banana",
    21: "Carrot",
    22: "Spaghetti squash",
    23: "Grapefruit",
    24: "Corn on the cob",
    25: "Cauliflower",
    26: "Lettuce",
    27: "Cabbage",
    28: "Eggplant",
    29: "Butternut squash",
    30: "Cucumber",
    31: "Coconut",
    32: "Jicama",
    33: "Pineapple",
    34: "Cantaloupe",
    35: "Honeydew melon",
    36: "Romaine lettuce head",
    37: "Swiss chard bunch",
    38: "Leek",
    39: "Mini watermelon",
    40: "Small pumpkin",
  },
  food: {
    4: "Grain of rice",
    5: "Orange seed",
    6: "Chocolate chip",
    7: "Coffee bean",
    8: "Kidney bean",
    9: "Olive",
    10: "Cherry tomato",
    11: "Brussels sprout",
    12: "Large shrimp",
    13: "Chicken nugget",
    14: "Slice of bread",
    15: "Dinner roll",
    16: "Hamburger patty",
    17: "Bagel",
    18: "Soft pretzel",
    19: "Croissant",
    20: "Cob of corn",
    21: "Small baguette",
    22: "Rack of ribs",
    23: "Large muffin",
    24: "Can of soda",
    25: "Head of broccoli",
    26: "Loaf of bread",
    27: "Large burrito",
    28: "Small pizza",
    29: "Rotisserie chicken",
    30: "Bunch of celery",
    31: "Large lobster",
    32: "Full baguette",
    33: "Two-liter soda bottle",
    34: "Large cabbage",
    35: "Small watermelon",
    36: "Large rotisserie chicken",
    37: "Loaf of French bread",
    38: "Large squash",
    39: "Honeydew melon",
    40: "Small pumpkin pie",
  },
  geeky: {
    4: "Pixel",
    5: "Tetris block",
    6: "Pac-Man ghost",
    7: "Game cartridge pin",
    8: "D20 die",
    9: "Pokéball",
    10: "Rubik's Cube corner",
    11: "Game Boy cartridge",
    12: "Hacky sack",
    13: "Action figure head",
    14: "Baby Yoda plush (mini)",
    15: "Nerf dart",
    16: "Collectible vinyl figure",
    17: "Funko Pop head",
    18: "Game controller (mini)",
    19: "Sandbox-game block",
    20: "Handheld console Joy-Con",
    21: "Lightsaber hilt",
    22: "Starship model (small)",
    23: "Death Star ornament",
    24: "Wookiee action figure",
    25: "Baby Groot pot",
    26: "Retro cartridge box",
    27: "Basketball (mini)",
    28: "Game controller",
    29: "Tabletop RPG rulebook",
    30: "Lightsaber",
    31: "Bowling pin",
    32: "Regulation football",
    33: "Retro boombox (mini)",
    34: "Basketball",
    35: "Gaming headset",
    36: "Skateboard deck (mini)",
    37: "Handheld game console",
    38: "Baseball bat (mini)",
    39: "Soccer ball",
    40: "Death Star (small model)",
  },
};

export const GROWTH_WEEKS: WeekData[] = STATS.map(([week, lengthCm, weightG, note]) => ({
  week,
  comparison: COMPARISONS.fruit[week],
  lengthCm,
  weightG,
  note,
}));

export function getWeekData(week: number, theme: ComparisonTheme = "fruit"): WeekData {
  const clamped = Math.min(Math.max(week, 4), 40);
  const stats = GROWTH_WEEKS.find((w) => w.week === clamped) ?? GROWTH_WEEKS[GROWTH_WEEKS.length - 1];
  return { ...stats, comparison: COMPARISONS[theme][clamped] };
}

// A real photo of each week's fruit/veg comparison (fruit theme only — the
// food/geeky comparisons don't have a matching real-world photo).
export function getFruitPhoto(week: number): string {
  const clamped = Math.min(Math.max(week, 4), 40);
  return `/images/growth/${clamped}.jpg`;
}
